### ISSUE TITLE
custom `content_font` doesn't apply

### ISSUE THREAD

**Issue by ndgnuh** [zzossig/hugo-theme-zzo#105]
Like the title stated, custom font setting doesn't work. I followed the guide in `README`.
`/` will refer to the root directory of the site.

`/assets/css/font.css` file:
```css
@font-face {
    font-family: 'merriweather';
    src: url('../fonts/Merriweather/Merriweather-Regular.ttf');
    src: url('../fonts/Merriweather/Merriweather-Regular.ttf') format('truetype');
    font-weight: 400;
    font-style: normal;
}
@font-face {
    font-family: 'comfortaa';
    src: url('../fonts/Comfortaa/static/Comfortaa-Regular.ttf');
    src: url('../fonts/Comfortaa/static/Comfortaa-Regular.ttf') format('truetype');
    font-weight: 900;
    font-style: normal;
}
```

`/data/font.toml` file:
```toml
title_font = "Comfortaa, sans-serif"
content_font = "Merriweather, serif"
```

`/config/_default/params.toml` file:
```toml
custom_css = ["css/font.css"]
```

`/statics` directory:
```shell
static
├── fonts
│   ├── Comfortaa
│   │   ├── Comfortaa-VariableFont:wght.ttf
│   │   ├── OFL.txt
│   │   ├── README
│   │   └── static
│   │       ├── Comfortaa-Bold.ttf
│   │       ├── Comfortaa-Light.ttf
│   │       ├── Comfortaa-Medium.ttf
│   │       ├── Comfortaa-Regular.ttf
│   │       └── Comfortaa-SemiBold.ttf
│   ├── Merriweather
│   │   ├── Merriweather-Black.ttf
│   │   ├── Merriweather-BlackItalic.ttf
│   │   ├── Merriweather-Bold.ttf
│   │   ├── Merriweather-BoldItalic.ttf
│   │   ├── Merriweather-Italic.ttf
│   │   ├── Merriweather-Light.ttf
│   │   ├── Merriweather-LightItalic.ttf
│   │   ├── Merriweather-Regular.ttf
│   │   └── OFL.txt
```

The title font setting does work. But the content one doesn't
![Screenshot_2020-01-25_17-38-02](https://user-images.githubusercontent.com/33273948/73119763-3205ab80-3f99-11ea-9164-d7a150f1d254.png)
