### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by fandean** [zzossig/hugo-theme-zzo#12]
Add border to the table, and set margin

![Snipaste_2019-11-26_04-32-27](https://user-images.githubusercontent.com/25637720/69582576-df992480-1013-11ea-9e07-3cfb22b6d48f.jpg)

![Snipaste_2019-11-26_02-23-53](https://user-images.githubusercontent.com/25637720/69582588-e6279c00-1013-11ea-9147-76bd699b3c0a.jpg)

Reduce the blockquote font size, cancel italics, and add margins

![Snipaste_2019-11-26_06-02-29](https://user-images.githubusercontent.com/25637720/69582888-87aeed80-1014-11ea-80ea-bdcfe6055f6b.jpg)

![Snipaste_2019-11-26_06-06-49](https://user-images.githubusercontent.com/25637720/69582671-0b1c0f00-1014-11ea-8b21-94c8258e88de.png)

![Snipaste_2019-11-26_06-11-52](https://user-images.githubusercontent.com/25637720/69582677-0fe0c300-1014-11ea-8c6d-5d4916589cf7.png)

and

![Snipaste_2019-11-26_00-56-39](https://user-images.githubusercontent.com/25637720/69582690-1707d100-1014-11ea-955c-06f4728deed3.png)

**Comment by zzossig** [comment]
Good suggestions thank you. But have some questions. What is the last picture means? And I think the blockquote style you suggest is not standard and normal. I’m afraid people may not recognize the blockquote. What is this blockquote style from? What about add it instead of replace it. We can name it blockquote2 or something

**Comment by fandean** [comment]
After observing the block quotes of many websites, I found that it was not appropriate for me to modify them like that. However, it is recommended to optimize it.
As for the last picture, don't you feel something wrong? I'm not very good at using words.

**Comment by zzossig** [comment]
Ok I also poor on English 😁. No worries. Anyway I’ll give it a try

**Comment by fandean** [comment]
Syntax highlighting is not available in the following languages
- bash/shell/sh
- yaml
- toml

![image](https://user-images.githubusercontent.com/25637720/69589075-b6818f80-1025-11ea-90fe-1002a2339a74.png)

In addition, when viewing the code against a dark background, the contrast is too high, which makes the eyes uncomfortable. I think the brightness of the code text should be reduced.

It would be nice if you could enable users to select syntax highlighting styles in configuration files in a way similar to the following
```toml
pygmentsUseClasses = false
pygmentsStyle = "monokai"
```
At the moment there are problems if you do that.

**Comment by kienct89** [comment]
for markdown table

you can put this in your `custom.css`

```css
table {
    border-spacing: 10px;
    border: solid 1px white;
}

table th,
table td {
    border-bottom: solid 1px white;
    padding: 0.5rem;
}
```

the table rendered will look like this

![image](https://user-images.githubusercontent.com/3182992/69601285-c02be700-1067-11ea-98f1-4b57e578f4f1.png)

**Comment by zzossig** [comment]
@fandean I made some changes. I agree that the color contrast on code block is so high so I adjusted it little a bit. I'll have to think more about syntax highlighting config param. And I think it's good idea.
As to blockquote styling, I prefer simple one. So I'll leave it as it is

**Comment by fandean** [comment]
I thought it might be better to just change the background color of the code block in the dark theme, so I changed it to look like this.Blockquote has been improved a lot. I think it is ok.Here's another little problem. See the picture. 
![image](https://user-images.githubusercontent.com/25637720/69620569-7ef00300-1078-11ea-9b29-7217f947433b.png)
This is my custom. scss
```scss
$code-font-stack: mononoki, "Cascadia Code",FiraCode, Consolas, "ubuntu mono", monospace;
$code-font-size: .95em; //默认为 0.9em
$content-pre-color: #b8b8b8;
$content-pre-background-color: #282c34;

.theme__dark .highlight>.chroma {
  color: $content-pre-color;
  background: $content-pre-background-color;

  table::after {
    //content-pre-header-color
    color: $content-pre-color;
    // content-pre-header-background-color
    background: darken($content-pre-background-color, 5%);
  }

  code, 
  pre {
    font-size: $code-font-size;
    font-family: $code-font-stack;
    background: $content-pre-background-color;
  }
}
```

---

Finally, I don't think you should specify the font "Montserrat" directly here. As I understand it, this will cause users who don't want to use "Montserrat" to download the font as well. Is my understanding correct?

https://github.com/zzossig/hugo-theme-zzo/blob/e5f6738ff643a644e914e9c7280d9e4917a06560/assets/sass/pages/_single.scss#L335
