### ISSUE TITLE
Add support telegram preview, instance view feature

### ISSUE THREAD

**Issue by zzossig** [zzossig/hugo-theme-zzo#122]
https://github.com/zzossig/hugo-theme-zzo/issues/90#issuecomment-580144221

**Comment by Gictorbit** [comment]
we're waiting impatiently 
perfect :+1:

**Comment by zzossig** [comment]
I'm trying to add the instance view feature.
But it seems that the code block not supported well.
![주석 2020-02-01 033628](https://user-images.githubusercontent.com/52706977/73564979-0e17fd80-44a4-11ea-82b3-33f606f92071.png)

The telegram instance view is just supported plain text.
If that is the case, do we have to have this feature?

**Comment by zzossig** [comment]
Also, the `zzo` theme load image lazy.
![주석 2020-02-01 034229](https://user-images.githubusercontent.com/52706977/73565457-e9705580-44a4-11ea-9659-dc88c8f55aac.png)

The instance view not quite well fit this project.
I think just a preview link would be fine.
![주석 2020-02-01 034535](https://user-images.githubusercontent.com/52706977/73565641-52f06400-44a5-11ea-89fb-eb54ab51f7be.png)

There are some limitations for adding the feature.

**Comment by Gictorbit** [comment]
ok, thank you so much for trying, if it's not possible to add this feature I think link preview would be fine and enough. instance view helps to readers but it's not necessary thanks

**Comment by zzossig** [comment]
I added the `whatsapp`, `telegram` share buttons.
I didn't test the preview link but I think it's working now.
One more thing that I changed the `featured_image` to `image`.

```
---
title:
date:
...
featured_image: whoami/avatar.jpg
image: images/whoami/avatar.jpg
---
```

Since featured_image is not included in the full relative path, the preview image is not shown.
So, I recommend to use `image` instead of `featured_image`

**Comment by Gictorbit** [comment]
I checked that and share buttons were great.
also added `image` to my post for preview link but it doesn't work in telegram and `image` couldn't load.
even  I used `@WebpageBot` for preview link and content updating in telegram
![image](https://user-images.githubusercontent.com/34630603/73572313-b9fe2080-4485-11ea-99ac-508eb9d68f1c.png)

**Comment by zzossig** [comment]
The `image` front matter is just alias for the `featured_image`.
The right syntax is

```yaml
featured_image: "post-image/2020/unlimited-storage.png"
image: "images/post-image/2020/google-drive.jpg"
```

Keep in mind that the `image` is just an alias to the `featured_image` and the `image` front matter has a full relative path(it includes `images` for the path)

I think the `image` front matter naming is not good. So, added new front matter named `meta_image`
So, you can do this.

```yaml
---
title: "دورزدن محدودیت حجم google drive"
date: 2020-01-26T19:45:41+03:30
description: "ذخیره نامحدود فایل ها در حساب گوگل"
draft: false
hideToc: false
enableToc: true
enableTocContent: false
tocPosition: outer
author: victor
authorEmoji: 😎
tags: 
- گوگل درایو
- python
- پایتون
categories:
- کاربردی
image: "images/post-image/2020/unlimited-storage.png"
meta_image: "images/post-image/2020/google-drive.jpg"
---
```

I just keep the `feature_image` front matter for the compatibility with an older version.
