### ISSUE TITLE
Dev.to in social icons

### ISSUE THREAD

**Issue by xdot26** [zzossig/hugo-theme-zzo#128]
Thanks for your  beautiful Hugo theme. Can we add dev.to icon?

**Comment by zzossig** [comment]
It's added. You can do this.

params.toml
```toml
...
[socialOptions]
  ...
  dev-to = "https://..."
```
