### ISSUE TITLE
feature request: support .bib/publications

### ISSUE THREAD

**Issue by brimwats** [zzossig/hugo-theme-zzo#138]
Hello!

The only reason I can't fully jump to zzo theme over a theme like [Academic ](https://github.com/gcushen/hugo-academic/) or [Academia ](https://github.com/themefisher/Academia-hugo) is because I need support for the publications import, which allows a bib file with publications to be imported.

It's documented here: https://sourcethemes.com/academic/docs/managing-content/#create-a-publication

Could this possibly be added as an external library? I tried to do that but the documentation wasn't super clear...and I'll admit that I didn't know what library they were using to do that :(

**Comment by zzossig** [comment]
Ok, I'll investigate what is the `publications import` and how to implement it

**Comment by brimwats** [comment]
thank you so much! I really appreciate it <3

**Comment by zzossig** [comment]
We can keep open until I do something on it

**Comment by zzossig** [comment]
I have a question.
I have tested the academic theme's publication.

This is my `.bib` file
```bib
@article{einstein,
    author =       "Albert Einstein",
    title =        "{Zur Elektrodynamik bewegter K{\"o}rper}. ({German})
        [{On} the electrodynamics of moving bodies]",
    journal =      "Annalen der Physik",
    volume =       "322",
    number =       "10",
    pages =        "891--921",
    year =         "1905",
    DOI =          "http://dx.doi.org/10.1002/andp.19053221004"
}

```

and this is generated file

```yaml
---
title: "Zur Elektrodynamik bewegter Körper. (German) [On the electrodynamics of moving bodies]"
date: 1905-01-01
publishDate: 2020-02-02T11:01:06.766549Z
authors: ["Albert Einstein"]
publication_types: ["2"]
abstract: ""
featured: false
publication: "*Annalen der Physik*"
doi: "http://dx.doi.org/10.1002/andp.19053221004"
---
```

This is what you expected behavior? It just generates the front matter, not the content.
If it does not generate the content, why do we need it?

I want to see what is the expected behavior when we import the .bib file.
Can you provide me some example .bib file?
