### ISSUE TITLE
Add Resume(CV) page

### ISSUE THREAD

**Issue by zzossig** [zzossig/hugo-theme-zzo#150]
https://github.com/zzossig/hugo-theme-zzo/issues/146#issuecomment-583754803

**Comment by zzossig** [comment]
Hello, @brimwats 
I uploaded the initial version of the resume page.
Update the theme first, and then follow the below steps

1. Make a folder and a file at `root/content/resume/index.md`
2. The `index.md` file looks like this.
```yaml
---
title: "Resume"
date: 2020-02-09T20:13:59+09:00
description: My awesome resume
type: resume
enableToc: false
header:
  image: 
    src: images/whoami/avatar.png
    height: 100
    alt: resume image
  infos:
    name: Choi
    email: cshl0ve@naver.com
    phone: 010-9887-1071
    website: www.exampleSite.com
    addr: 서울시 ㄴㅁㅇㅅ먼ㅇㅅ
items:
  - title: myTitle
    sections:
      - title: sectionTitle1
        subtitle: sectionSubtitle1
        startDate: 2020-02-09T20:13:59+09:00
        endDateText: current
        endDate: 2020-02-10T20:13:59+09:00
        contents: | 
          # h1
          ## h2
          ### h3
          1. hele
          2. dasg
          3. 125
          - bbb
          - eee
          - qqq
          > asdignasg

          [heeeee](https://google.com)

      - title: sectionTitle2
        subtitle: sectionSubtitle2
        date: 2020-02-07T20:13:59+09:00
        contents: | 
          Describe your role here lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo.

          Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.
      - title: sectionTitle3
        subtitle: sectionSubtitle3
        date: 2020-02-05T20:13:59+09:00
        contents: | 
        
  - title: myTitle2
    sections:
      - title: sectionTitle2-1
        subtitle: sectionSubtitle2-1
        date: 2020-02-09T20:13:59+09:00
        contents: | 
        
      - title: sectionTitle2-2
        subtitle: sectionSubtitle2-2
        date: 2020-02-07T20:13:59+09:00
        contents: | 
        
      - title: sectionTitle2-3
        subtitle: sectionSubtitle2-3
        date: 2020-02-05T20:13:59+09:00
        contents: | 
        
---

```

3. Edit the params to yours. Leave the params empty or delete if you don't want to set the params.
4. Be careful that the contents param accept a markdown syntax. It should start with `|` and the contents should one level more deep than it's key(contents)
5. You can set as many items as you want like this.
```yaml
...
items:
  - title:
    sections:
  - title:
    sections:
  - title:
    sections:
...
```

**Comment by knightdave** [comment]
Hi, I found one issue here -  `endDate` is not formatted with `resume-dateformat` - it use some other one.

![image](https://user-images.githubusercontent.com/13086223/74138198-70ce6f00-4bf1-11ea-82b3-5da5c2f1f935.png)

**Comment by zzossig** [comment]
How did you set `defaultContentLanguage` in the `config.toml` file?

**Comment by knightdave** [comment]
`config.toml`
```toml
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
hasCJKLanguage = false
```

`i18n/en.toml`
```toml
[pub-dateformat]
other = "2006-01-02"

[resume-dateformat]
other = "Jan, 2006"
```

`i18n/pl.toml`
```toml
[pub-dateformat]
other = "2006-01-02"

[resume-dateformat]
other = "2006"
```


English version looks like that:

![image](https://user-images.githubusercontent.com/13086223/74138941-c8210f00-4bf2-11ea-9a79-a0bb8f950807.png)
