### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by LGTMXD** [zzossig/hugo-theme-zzo#154]
## 2. support Google Adsense
![image](https://user-images.githubusercontent.com/30213081/74121499-c0696680-4c02-11ea-9587-c8fdfc7521f8.png)

paste code between `</head> ` , then put [ads.txt](https://support.google.com/adsense/answer/7532444?hl=en) to your website root directory

## 3. Search Part

- Option 1:     Support third-party search engine ：[Algolia search](https://www.algolia.com/search/)

- Option 2： Support buid-in search engine

> example here from hugo theme [acdamic](https://sourcethemes.com/academic/)，when you type `/` (keyboard shortcut) , your cursor quickly into search bar.[source code on GitHub](https://github.com/gcushen/hugo-academic/search?q=search&unscoped_q=search)

![image](https://user-images.githubusercontent.com/30213081/74120987-872ff700-4c00-11ea-8706-160e3ca68b06.png)

## 4. Add Terms and Privacy in footer，
![image](https://user-images.githubusercontent.com/30213081/74120731-83e83b80-4bff-11ea-9870-336ee5b6e470.png)

## 5. Add Privacy pack :Show a cookie consent message to visitors

![image](https://user-images.githubusercontent.com/30213081/74121239-b5fa9d00-4c01-11ea-9dd9-018b15a012e7.png)

**Comment by zzossig** [comment]
Ok, this makes sense.
I'll add all of them. But
> when you type / (keyboard shortcut) , your cursor quickly into search bar.

I don't want to set a global key down event for the search.
You do make a custom js file if you want the feature.

**Comment by LGTMXD** [comment]
> Ok, this makes sense.
> I'll add all of them. But
> 
> > when you type / (keyboard shortcut) , your cursor quickly into search bar.
> 
> I don't want to set a global key down event for the search.
> You do make a custom js file if you want the feature.

Okay  #154

## 6. add netlify.toml

* website host on netlify.com , which needs custom netlify.toml file, example blew

- use **301 URL redirection** ,thus, i could use my own domain instead of second-level domain of netlify.com  changing `https://zzodocs.netlify.com/`  to  `https://zzodocs.com`

- 301 moved permanently (redirects permanently from one URL to another passing link equity to the redirected page)


```toml
[build]
  command = "hugo --gc --minify -b $URL"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.62.0"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[[headers]]
  for = "*.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json; charset=UTF-8"

[[headers]]
  for = "index.xml"
  [headers.values]
    Content-Type = "application/rss+xml"

[[redirects]]
  from = "https://zzo.netlify.com/*"
  to = "https://zzo.com/:splat"
  status = 301
  force = true
  # query = {path = ":path"}
  # conditions = {Language = ["en"], Country = ["US"], Role = ["admin"]}

```


- [[redirects]]: 

[redirects usage from netlify doc](https://docs.netlify.com/routing/redirects/#syntax-for-the-redirects-file)

**Comment by zzossig** [comment]
Netlify is not part of this project.
But did you mean that I should make documentation on how to host a site using Netlify?
It's documented here https://gohugo.io/hosting-and-deployment/hosting-on-netlify/#readout

**Comment by zzossig** [comment]
@LGTMXD 
I have a question.
What's the benefit of adding Algolia?
I just found that Algolia uses the `instantsearch.js` library and It's almost the same with the current search engine in the zzo theme. It adds complexity.

Since I don't want to manage the two search engines, I want you to explain the benefit of the Algolia.
Why are you not satisfying the current search? How about I improve the current search instead of adding Algolia?

Regarding Google Adsense, you have to override the `layouts` folder to control the ads.
For example, make this file to your partials folder.
```javascript
{{ if and (not .Site.IsServer) (not ($.Param "disableAdsense")) }}
  <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
  <ins
    class="adsbygoogle"
    style="display:block; text-align:center;"
    data-ad-layout="in-article"
    data-ad-format="fluid"
    data-ad-client="ca-pub-xxxxxx"
    data-ad-slot="xxxxx"
  >
  </ins>
  <script>
    (adsbygoogle = window.adsbygoogle || []).push({});
  </script>
{{ end }}
```
And then, insert this partial by overriding theme's layout folder.(so to speak, make your layout folder at your root directory and copy files from the theme's directory. that is the override)
I don't think this doesn't have to be part of the theme. The user has to add it.
I'll wait for your feedback. You can just type Chinese.

**Comment by LGTMXD** [comment]
没有原因，就是想用。

**Comment by zzossig** [comment]
You can add google tag manager by setting `googleTagManager` parameter
```toml
...
googleTagManager = "" #GTM-XXXXXX
```

You can also add links to the footer by setting the below parameter
```toml
...
[[footerLinks]]
  name = "privacy"
  link = "https://..."
[[footerLinks]]
  name = ""
  link = ""
```
