### ISSUE TITLE
series flag doesn't work

### ISSUE THREAD

**Issue by Gictorbit** [zzossig/hugo-theme-zzo#171]
I added the series flag to my post like categories and tags but it doesn't appear in the series section is it a bug or I made a mistake somewhere?

**Comment by zzossig** [comment]
How did you set it in the front-matter?

**Comment by Gictorbit** [comment]
I did it too, this is my latest posts `front-matter` in the below link as you can see the series flag is there 
[photoshop.md](https://raw.githubusercontent.com/Gictorbit/myblog/master/content/posts/GnuLinux/photoshop.md)

**Comment by zzossig** [comment]
I found that you have the wrong config params.

```toml
[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"
```

for the search, in your `config.toml` file
```toml
[outputs]
  page = ["HTML", "SearchIndex"]
  home = ["HTML", "RSS", "SearchIndex"]
  section = ["HTML", "RSS", "SearchIndex"]
  taxonomyTerm = ["HTML", "RSS", "SearchIndex"]
  taxonomy = ["HTML", "RSS", "SearchIndex"]

[outputFormats]
  [outputFormats.SearchIndex]
    mediaType = "application/json"
    baseName = "index"
    isPlainText = true
    notAlternative = true
```

In your `params.toml` file
```toml
searchResultPosition = "side" # side, main
```
