### ISSUE TITLE
[Feature] Showcase section should allow generic card

### ISSUE THREAD

**Issue by nisrulz** [zzossig/hugo-theme-zzo#172]
I am trying to add patents to my showcase section. 

![Screenshot from 2020-02-16 01-29-30](https://user-images.githubusercontent.com/2096087/74597235-210dfe80-505c-11ea-9577-79d7cbe19125.png)

Notice that this is not code, so `</> Patents` is wrong with `</>`.
Also `Repository` is also wrong as text with github icon in this context.

Suggestion:
There are two more fields in the meta data part for the page:
- download: This will be a simple download link. People can use it for any generic download link. Probably will also have a generic download file icon.
- _index.md for category i.e Patents/_index.md has `type` as metadata. Type can be
    - Code
    - Generic

Thoughts?

**Comment by nisrulz** [comment]
Another category I have is `Books`.

**Comment by zzossig** [comment]
Hello!😋
I think it's a good feature to have!
I'll make it anyway. 
And then can talk to improve it

**Comment by zzossig** [comment]
I added `categoryIcon` front-matter in `_index.md` file.

`showcase/hugo/_index.md`
```yaml
---
title: "Hugo"
date: 2020-01-19T21:04:11+09:00
description: Hugo theme collection
category: theme
categoryIcon: 'code'
enableBio: false
---
```

Possible `categoryIcon` value: `author` `book` `certificate` `code` `download` `github` `reviewer`
default value is `code`

Also, I added option for links

In your `md` file e.g: `showcase/hugo/hugo-theme-zzo.md`

```yaml
...
links:
- name: download
  icon: download
  link: https://github.com/gohugoio/hugo/releases/download/v0.64.1/hugo_extended_0.64.1_Windows-64bit.zip
- name:
  icon:
  link:
...
```

The possible icon would be same as above.
