### ISSUE TITLE
Optional putting post content in RSS feed

### ISSUE THREAD

**Issue by szpak** [zzossig/hugo-theme-zzo#180]
Optionally (disabled by default) it could be also possible to put also the whole content of the post in the RSS feed - `<content:encoded>` (probably also with `<media:content>`).

Sample [feed with content](https://solidsoft.wordpress.com/feed/).

**Comment by zzossig** [comment]
I added all of them

`params.toml`
```toml
...
updatePeriod = "" # Possible values: 'hourly', 'daily', 'weekly', 'monthly', or 'yearly'.
updateFrequency = ""
fullContents = false
```
