### ISSUE TITLE
how can I change navbar menu direction?

### ISSUE THREAD

**Issue by Gictorbit** [zzossig/hugo-theme-zzo#189]
in my blog when I switch between languages, menu direction changes because of RTL mode.
is there any parameter for `param.toml` to set direction?

**Comment by zzossig** [comment]
No, we don't have options for it.
Do you want to keep navbar direction the same with the LTR  when RTL?

**Comment by Gictorbit** [comment]
yes I think ltr direction for the menu is better than rtl direction
but It would be perfect if you add this option, It can be used for each `menus.toml` config

**Comment by zzossig** [comment]
You can set `navbardir` in `languages.toml` file

```toml
[en]
  title = "Zzossig's Blog"
  languageName = "English"
  weight = 2
  languagedir = "ltr"
  contentdir = "content/en"
  navbardir = "ltr"
```
