### ISSUE TITLE
Paginate Error.

### ISSUE THREAD

**Issue by bootyocean18** [zzossig/hugo-theme-zzo#199]
Hey! Love the theme. I've been playing around with it and it's beautifully put together. I really appreciate your work. I've been able to root around and debug most problems myself, but here's one I've come up (starting last night) that I can't seem to sort out:

```
Error: Error building site: failed to render pages: render of "section" failed: "/opt/build/repo/themes/zzo/layouts/archive/list.html:19:21": execute of template failed: template: archive/list.html:19:21: executing "main" at <.Paginate>: error calling Paginate: cannot convert type page.PagesGroup to Pages
```
I'm running CI/CD through Netlify and GitLab. 

I have updated the theme locally and in repo, I am deploying with Hugo 0.65.3

My repo is at: https://gitlab.com/rizdy/svrty

**Comment by zzossig** [comment]
Hi, Thanks,😋
I tested the zzo theme with Hugo 0.65.3 and it works well.
How can I reproduce it?
Can you provide me a repository so that I can test it on my end?

**Comment by bootyocean18** [comment]
https://gitlab.com/rizdy/svrty
Sorry I didn't make it public earlier.

**Comment by zzossig** [comment]
The error may have happened because there is no post at all.
I found that you have just 1 post and there, you set `draft: false` which means, you don't want to publish the post when deployed.
So try this

```yaml
---
title: A Proper View of Ascetics
date: 2020-02-22T12:00:06+09:00
description: Maintaining a proper view of ascetic discipline within Christianity.
draft: false ##### set draft to false #####
...
series: ##### series data structure should be array, not string. #####
- Intro to Ascetics
---
```
