### ISSUE TITLE
[Feature request] a twitch icon for linking your stream

### ISSUE THREAD

**Issue by sim590** [zzossig/hugo-theme-zzo#211]
In the set of social links parameters, an entry for twitch your stream could be cool.

**Comment by zzossig** [comment]
I added Twitch icon.
Update the theme first and you can use it like this

`params.toml`
```toml
[socialOptions]
...
twitch = "url"
...

```
