### ISSUE TITLE
cancel the root directory of the album

### ISSUE THREAD

**Issue by redisread** [zzossig/hugo-theme-zzo#215]
I want to ask how to cancel the root directory of the album?because my picture is in the drawing bed, and the drawing bed is faster

**Comment by zzossig** [comment]
Hey~ Sorry, I don't understand
You can just type Chinese And I'll use google translate

**Comment by nisrulz** [comment]
@redisread you can just update your menu.toml file to refer to the direct link i.e 

[This](https://github.com/zzossig/hugo-theme-zzo/blob/master/exampleSite/config/_default/menus.en.toml#L19-L33): 

```
[[main]]
  identifier = "gallery"
  name = "Gallery"
  url = "gallery"
  weight = 4
    
[[main]]
  parent = "gallery"
  name = "Cartoon"
  url = "gallery/cartoon"

[[main]]
  parent = "gallery"
  name = "Photo"
  url = "gallery/photo"
```

Can be replaced by:

```
[[main]]
  identifier = "gallery"
  name = "Gallery"
  url = "gallery/drawing-bed"
  weight = 4
```

You need to update the url field and get rid of sub menu items.

**Comment by redisread** [comment]
> Hey~ Sorry, I don't understand
> You can just type Chinese And I'll use google translate

好的。我的问题是:
在相册页面中你设置了根目录为images，图片链接类似:images/a/jpg,但是我不想将我的图片存储在github上面，因为在中国GitHub的速度有点慢，我想用自己的图片链接，就像这样:https://i.loli.net/2020/03/02/GabXC4JmfN6H2hE.png.我希望能够在相册页面中使用这样的图片链接而不是文件的相对链接。你能帮助我吗？

**Comment by redisread** [comment]
> @redisread you can just update your menu.toml file to refer to the direct link i.e
> 
> [This](https://github.com/zzossig/hugo-theme-zzo/blob/master/exampleSite/config/_default/menus.en.toml#L19-L33):
> 
> ```
> [[main]]
>   identifier = "gallery"
>   name = "Gallery"
>   url = "gallery"
>   weight = 4
>     
> [[main]]
>   parent = "gallery"
>   name = "Cartoon"
>   url = "gallery/cartoon"
> 
> [[main]]
>   parent = "gallery"
>   name = "Photo"
>   url = "gallery/photo"
> ```
> 
> Can be replaced by:
> 
> ```
> [[main]]
>   identifier = "gallery"
>   name = "Gallery"
>   url = "gallery/drawing-bed"
>   weight = 4
> ```
> 
> You need to update the url field and get rid of sub menu items.

en，I want to use link such as https://i.loli.net/2020/03/02/GabXC4JmfN6H2hE.png......

**Comment by zzossig** [comment]
您知道图库页面具有一对一模式吗？
您想尝试以下代码吗？
```yaml
---
title: "My Gallery"
date: ""
description: ""
type: gallery
mode: one-by-one # at-once or one-by-one
images: 
  - image: "https://i.loli.net/2020/03/02/GabXC4JmfN6H2hE.png......"
    caption: caption1
  - image: "https://i.loli.net/2020/03/02/GabXC4JmfN6H2hE.png......"
    caption: caption2
    ...
---
```

**Comment by redisread** [comment]
> 您知道图库页面具有一对一模式吗？
> 您想尝试以下代码吗？
> 
> ```yaml
> ---
> title: "My Gallery"
> date: ""
> description: ""
> type: gallery
> mode: one-by-one # at-once or one-by-one
> images: 
>   - image: "https://i.loli.net/2020/03/02/GabXC4JmfN6H2hE.png......"
>     caption: caption1
>   - image: "https://i.loli.net/2020/03/02/GabXC4JmfN6H2hE.png......"
>     caption: caption2
>     ...
> ---
> ```
> 
> 我没有测试，但是尝试一下

我试过了，不行，他会从根目录images中找，这样找不到图片。

**Comment by zzossig** [comment]
好啦 让我们添加一个新选项。

**Comment by zzossig** [comment]
@redisread
向图库页面添加了新选项。尝试这样的事情：

```yaml
---
title: "My Gallery"
date: ""
description: ""
type: gallery
mode: remote
images: 
  - image: "https://i.loli.net/2020/03/02/GabXC4JmfN6H2hE.png......"
    caption: caption1
  - image: "https://i.loli.net/2020/03/02/GabXC4JmfN6H2hE.png......"
    caption: caption2
    ...
---
```
