### ISSUE TITLE
No option to hide "See also" in post view

### ISSUE THREAD

**Issue by pashinskikh** [zzossig/hugo-theme-zzo#236]
Hi! Is there's an option to disable "See also" and author info in post view?

**Comment by zzossig** [comment]
I think we have one.
In your markdown file,
```yaml
---
title: 
date:
...
enableToc:  false # disable toc
---
```

You can check all front-matter options in `theme/zzo/archetypes` folder
