### ISSUE TITLE
How to remove underline of links?

### ISSUE THREAD

**Issue by mayan-lab** [zzossig/hugo-theme-zzo#245]

**Comment by fandean** [comment]
You can try to add the following code to your custum.css file
```css
a {
  text-decoration-line: none !important;
}
```
