### ISSUE TITLE
发布后文件过大

### ISSUE THREAD

**Issue by iamwlb** [zzossig/hugo-theme-zzo#252]
使用zzo模版以后，会导致发布后的文件过大，一般的供应商都很难支持这么大的文件。
看了下，主要导致过大的原因有：
1. 太多的index.json和index.xml文件。
2. tags文件夹过大
针对这些问题，可否尽快做下优化？

**Comment by fandean** [comment]
你可以尝试，将 config.toml 中的 outputs 修改成下面这样：

```toml
[outputs]
  page = ["HTML"]
  home = ["HTML", "RSS", "SearchIndex"]
  section = ["HTML", "RSS", "SearchIndex"]
  taxonomyTerm = ["HTML"]
  taxonomy = ["HTML"]
```
