### ISSUE TITLE
valine not working

### ISSUE THREAD

**Issue by dxb22abad** [zzossig/hugo-theme-zzo#30]
Set up in /root/layouts/partials/valien.html as well as in /root/config/_default/params.toml
All selected "true" or enable. but there is no visitor numbers on any pages.
Any ideas?

Your theme is awesome, BTW

**Comment by zzossig** [comment]
Did you set the params below to yours?
```toml
...
[valine]
  enable = false
  appId = '你的appId'
  appKey = '你的appKey'
  notify = false  # mail notifier , https://github.com/xCss/Valine/wiki
  verify = false # Verification code
  avatar = 'mm' 
  placeholder = '说点什么吧...'
  visitor = false
...
```
