### ISSUE TITLE
Links to post incorrect (nginx reverse proxy)

### ISSUE THREAD

**Issue by Biskit1943** [zzossig/hugo-theme-zzo#316]
Hey,

first of all, very nice theme - I love it! But I have one small problem, the links to the posts on the main page are incorrect when serving this site via docker.

Here is the page: https://m-konter.de/

The main menu is completely correct, so for example `About Me` resolves correctly to https://m-konter.de/about/ but clicking on `My first post!` will resolve to `http://localhost:1313/posts/first-post/` which is wrong.

I'm not completely sure if this error is from your theme or from Hugo. The configuration I use this hosted here: https://github.com/Biskit1943/website .

I'm running this website via docker-compose and a reverse proxy (nginx), here is my `docker-compose.yml`

```yaml
version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: reverse_proxy
    restart: unless-stopped
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  hugo:
    image: klakegg/hugo:latest-ext
    container_name: website
    volumes:
      - ./data/hugo:/src
    command: server
    environment:
      - HUGO_ENV=production
```

Thanks in Advance,

Max
