### ISSUE TITLE
Gallery images are stretched on Safari

### ISSUE THREAD

**Issue by creativeprojects** [zzossig/hugo-theme-zzo#326]
In Safari on macOS the gallery images are stretched to their full height.

There's a description of the issue on stack overflow and a JSFiddle for the fix: https://stackoverflow.com/questions/57516373/image-stretching-in-flexbox-in-safari

I had a look at it, and I managed to fix it simply by adding `align-items: flex-start;` in _gallery.scss:

```css
.gallery {

    .grid-item {

        align-items: flex-start;

    }

}
```

It doesn't seem to be any issue on the other browsers I tried.

I can send a pull-request if you prefer so

Thanks for your hard work 👍🏻
