### ISSUE TITLE
Responsive rows and column in post body.

### ISSUE THREAD

**Issue by odunayo12** [zzossig/hugo-theme-zzo#346]
Hi there @SathyaBhat and @zzossig, things working fine so far and kudos to you all. The theme worked fine with Forestry as CMS. Wondering if there can be functionality such that some sections of a post can be put in responsive rows and columns. My efforts:
created `_cards.scss`  with 
```CSS
.cards {
  max-width: 960px;
  margin: 0 auto;
  display: grid;
  grid-gap: 1rem;
  grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
}

```

and `_card.scss` 
```CSS
.card {
  padding: 4rem;
  border-radius: 0.5rem;

  @include themify($themes) {
    border: 1px solid themed("content-box-border-color");
    background-color: themed("content-box-background-color");
  }
}

```
in `assets\sass\components` with the above codes respectively.

Secondly, created `cards.html` with 
```html
<div class="cards">{{ .Inner }}</div>
```
and  `card.html` with 
```html
<div class="card">{{ .Inner }}</div>
```
in  `layouts\shortcodes`.

After which I used the following shortcodes in my  `markdown` file like so
```go
{{< cards >}}
{{< card>}}Eyes {{< /card>}}
{{< card>}}Nose{{< /card>}}
{{< card>}}Mouth{{< /card>}}
{{< card>}}Teeth{{< /card>}}
{{< /cards >}}
```

Kindly find my expectation on  [`codepen.io`](https://codepen.io/odunayo12/pen/OJXoGKd)  and the reality below
![image](https://user-images.githubusercontent.com/19196838/98457976-3bf54580-218c-11eb-869f-cd78bc2252e9.png)

Your advice is well appreciated. Thanks in advance.
PS: If you also want me to document how to use the theme with forestry. I would gladly to that to enhance the usability.
