### ISSUE TITLE
Update Mermaid version to 8.8.4

### ISSUE THREAD

**Issue by javydekoning** [zzossig/hugo-theme-zzo#379]
Hi there @zzossig could you update the mermaid version please?

```toml
[js.mermaid]
sri = "sha256-/+BzMP7spK5kZq/eJyTUBpewugOb45C/VbvZkziFAB4="
url = "https://cdn.jsdelivr.net/npm/mermaid@8.8.4/dist/mermaid.min.js"
```

Thanks 👋
