### ISSUE TITLE
Talks page media links.

### ISSUE THREAD

**Issue by kkYrusobad** [zzossig/hugo-theme-zzo#425]
I read the documentation but was unable to find information regarding linking of a presentation to a post on talks tab.
There must be something I am missing, though i don't know what.

**Comment by szpak** [comment]
I'm not sure what are you intentions, but here is a sample page for a talk:
```
title: "Spock vs JUnit 5 - Clash of the Titans, Greach, Madrit, Spain"
publishDate: 2019-03-29
disableLink: true
subLinks:
- type: slide
  link: https://speakerdeck.com/szpak/spock-vs-junit-5-clash-of-the-titans
- type: video
  link: https://www.youtube.com/watch?v=xxx
```
which is rendered as:
![image](https://user-images.githubusercontent.com/148013/122820836-5b388180-d2dc-11eb-90d9-e8fd83b1b399.png)

`disableLink: true` is only to disable creating a separate page for that talk - only links to media (could be your linked post).
