### ISSUE TITLE
Titles above level 4 are not rendered to toc.

### ISSUE THREAD

**Issue by Codeapes666** [zzossig/hugo-theme-zzo#57]
hi, I found that my article only shows one level of directories, but I added multiple levels.

**Comment by zzossig** [comment]
Can you show me how your folder structures are?
![주석 2020-01-01 134144](https://user-images.githubusercontent.com/52706977/71638186-7bb1ed80-2c9c-11ea-9884-c165a9963e54.png)
I tested it on my local environment but it works well

**Comment by Codeapes666** [comment]
![357D6605-953D-4F12-BF64-D0020A759818](https://user-images.githubusercontent.com/48265970/71643180-163c1c00-2cf1-11ea-9b8d-50cd0700a580.jpeg)

I am talking about this directory. Use markdown , ####can show, but##### don’t show.

**Comment by zzossig** [comment]
Can you update the Zzo theme to the latest version?
and then, edit your config file at root/config/_default/confi.toml
```toml
...
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = true
      unsafe = true
      xHTML = true
  [markup.highlight]
    codeFences = true
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
...
```
